In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
import sys
print(sys.executable)

C:\Users\yadav\AppData\Local\Programs\Python\Python313\python.exe

In [8]:
!pip install ydata-profiling

Requirement already satisfied: ydata-profiling in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (1.16.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (2.3.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (2.13.5)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (2.3.2)
Requirement already satisfied: minify-html>=0.15.0 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (2.34.2)
Requirement already satisfied: tqdm<5,>=4.66.3 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (4.70.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (0.15.0)
Requirement already satisfied: typeguard<5,>=4 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (4.6.0)
Requirement already satisfied: imagehash==4.3.2 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.10.0)
Requirement already satisfied: pillow in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from imagehash==4.3.2->ydata-profiling) (12.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.4)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.1)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.46.5)
Requirement already satisfied: typing-extensions>=4.14.1 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.7.22)
Requirement already satisfied: patsy>=0.5.6 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.3)
Requirement already satisfied: formulaic>=1.1.0 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.2.2)
Requirement already satisfied: colorama in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.7)
Requirement already satisfied: puremagic in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: interface-meta>=1.2.0 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from formulaic>=1.1.0->statsmodels<1,>=0.13.2->ydata-profiling) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from formulaic>=1.1.0->statsmodels<1,>=0.13.2->ydata-profiling) (2.26.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from formulaic>=1.1.0->statsmodels<1,>=0.13.2->ydata-profiling) (2.5.0)
Requirement already satisfied: six>=1.5 in C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [10]:
import pandas as pd

df = pd.read_csv("train.csv")

from ydata_profiling import ProfileReport

prof = ProfileReport(df)
prof.to_file("output.html")

C:\Users\yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\yadav\AppData\Local\Temp\ipykernel_22508\3210408046.py:5: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport
Summarize dataset:  35%|███▌      | 6/17 [00:00<00:01,  6.95it/s, Describe variable: Embarked]
Summarize dataset:  71%|███████   | 12/17 [00:00<00:00, 21.57it/s, Describe variable: Embarked]
100%|██████████| 12/12 [00:00<00:00, 100.33it/s][A
Summarize dataset: 100%|██████████| 47/47 [00:06<00:00,  7.82it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:06<00:00,  6.30s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.29s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 39.45it/s]